import { upsertAirport, upsertLounge, getAirport } from './db.js';
export function seed(){
 if(getAirport('DOH')) return;
 const now=new Date().toISOString();
 upsertAirport({code:'DOH',name_en:'Doha Hamad International',name_vi:'Doha Hamad International',terminals:['South Node','North Node'],updated_at:now,last_success_at:'',source_status:'cache',last_error:''});
 const rows=[
 {lounge_code:'DOH1',name_en:'Al Maha Lounge (South Node)',terminal:'South Node',opening_en:'Open 24 hours daily. Peak periods: 17:00–19:00, 22:00–02:00 and 04:00–07:00. Access may be periodically restricted due to space constraints.',opening_vi:'24 giờ mỗi ngày. Lưu ý: Do các khung giờ cao điểm (17:00 - 19:00; 22:00 - 02:00 và 04:00 - 07:00), dự kiến số lượng khách tại khu vực này sẽ tăng lên. Do đó, việc ra vào có thể bị hạn chế theo từng đợt do không gian có hạn.',location_en:'Airside - Level 2 of Duty Free South. From the Teddy Bear, walk straight ahead and use the lift or escalator on the left. The lounge is near Gates A, B and C.',location_vi:'Khu vực sân bay - Tầng 2 của Duty Free South. Từ Khu Gấu Bông, đi thẳng về phía trước và sử dụng thang máy hoặc thang cuốn bên trái. Phòng chờ nằm gần các cổng A, B và C.'},
 {lounge_code:'DOH2',name_en:'Sleepover (South Node)',terminal:'South Node',opening_en:'Open 24 hours daily. Single FlexiSuite stay is limited to 3 hours, available from 08:00 to 22:00. Cardholders only during these hours.',opening_vi:'24 giờ mỗi ngày. Lưu ý: Thời gian lưu trú 3 giờ tại phòng Single FlexiSuite (tối đa 1 khách) – từ 08:00 đến 22:00. Chỉ chủ thẻ mới được phép vào địa điểm này trong khung giờ trên.',location_en:'Airside - premium duty free area near Gates B, approximately 2 minutes from the Teddy Bear sculpture.',location_vi:'Airside - tọa lạc tại khu vực miễn thuế cao cấp, gần các cổng B, cách tác phẩm điêu khắc Gấu Bông khoảng 2 phút đi bộ.'},
 {lounge_code:'DOH3',name_en:'Sleepover (North Node)',terminal:'North Node',opening_en:'Open 24 hours daily. 2-hour Nap Pod stay includes cotton sheets, pillow and blanket, plus 30 minutes premium shower room use.',opening_vi:'24 giờ mỗi ngày. Lưu ý: Thời gian nghỉ 2 giờ trong buồng ngủ Nap Pod (bao gồm ga trải giường bằng cotton, gối và chăn) – kèm theo 30 phút sử dụng phòng tắm cao cấp.',location_en:'Airside - Transit Area, Ground Floor, Concourse C, opposite Gates C30–31. International and transit flights only.',location_vi:'Khu vực sân bay - Khu vực quá cảnh, Tầng trệt, Cổng C, đối diện các cổng C30 - 31. Chỉ dành cho các chuyến bay quốc tế và các chuyến bay quá cảnh.'}
 ];
 for(const r of rows) upsertLounge({airport_code:'DOH',...r,name_vi:r.name_en,conditions_en:'',conditions_vi:'',facilities_en:'',facilities_vi:'',notes_en:'',notes_vi:'',source_url:`https://loungefinder.loungekey.com/en/linkcarevn/lounge-detail/?airportcode=DOH&loungecode=${r.lounge_code}`,image_url:'',updated_at:now});
}
